### ISSUE TITLE
Failed to resolve platforms: Could not read directory.

### ISSUE THREAD

**Issue by Haelikor** [JMBeresford/retrom#149] opened 2024-10-11 03:41 UTC
I've seen this issue elsewhere but couldn't seem to fix it using their solutions.

Error:

` 2024-10-11T03:12:37.257977Z  WARN update_library:update_library: retrom_service::grpc::library::update_handlers: Failed to resolve platforms: Could not read directory`

[[Docker-Compose]]

```yml
services:
  retrom:
    image: ghcr.io/jmberesford/retrom-service:latest
    ports:
      - 5101:5101
      - 3000:3000 # to access the web client
    volumes:
      - /mnt/gaming/retrom/config:/config # directory containing your config file
      - /mnt/gaming/roms:/library1 # directory containing your first library
    networks:
      - internal

  retrom-db:
    container_name: retrom-db
    hostname: retrom-db # this should match the db_url in your config file
    image: postgres:16
    restart: unless-stopped
    volumes:
      # to store the DB data on the host, change this path to any directory you like
      - /mnt/gaming/retrom/retrom_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: guesswho # db user, used to connect to the db, should match the db_user in your config file
      POSTGRES_PASSWORD: specialpassword # db password for above user, should match the db_password in your config file
      POSTGRES_DB: retrom # db name, should match the db_name in your config file
    networks:
      - internal

networks:
  internal:
    external: true
```

[[Config]]
    

```json
{
  "connection": {
    "port": 5101,
    "db_url": "postgres://myusername:mycoolpassword@retrom-db/retrom"
  },
  "content_directories": [
    {
      "path": "/library1",
      "storage_type": "SingleFileGame"
    }
  ],
  "igdb": {
    "client_secret": "verycool",
    "client_id": "ultraawesome"
  }
}
```

My understanding:

Just mounting the one library type, SingleFileGame since I keep my roms one directory down from each platform. The container can access my games location, my mounts seem fine:

![image](https://github.com/user-attachments/assets/f5c53df3-74c2-4934-ba26-7e2d0188f300)
![image](https://github.com/user-attachments/assets/bab1acac-726c-4bb5-befa-d69dac59670b)

I appreciate any advice/help, neat project!

**Comment by JMBeresford** [comment] 2024-10-11 05:10
Would you add the following to your docker compose file and restart the service to recollect the logs:

```yml
services:
  retrom:
    environment: # add this block
      - RUST_LOG=debug
```

Also can you show me the inside of your platform dirs?

Also what version of Retrom are you using here?

**Comment by Haelikor** [comment] 2024-10-11 05:44
Sure thing, added and restarted.

![image](https://github.com/user-attachments/assets/156c9ceb-2077-44e4-bb7c-81c36c7d9f9d)

Here is an example of inside a platform directory. 

Structure is library -> platform -> individual game files for above platform.

This is with a brand new install, v0.2.0.

On restarting container, first logs:

> 2024-10-10 22:37:09 2024-10-11T05:37:09.076011Z  INFO retrom_service: Starting server at: 0.0.0.0:5101
> 2024-10-10 22:37:09 
> 2024-10-10 22:37:09 > web@ preview /app/web
> 2024-10-10 22:37:09 > vite preview
> 2024-10-10 22:37:09 
> 2024-10-10 22:33:18 Failed to read local Cargo.toml: Error: ENOENT: no such file or directory, open '/Cargo.toml'
> 2024-10-10 22:33:18     at Object.openSync (node:fs:573:18)
> 2024-10-10 22:33:18     at readFileSync (node:fs:452:35)
> 2024-10-10 22:33:18     at readLocalCargoToml (file:///app/web/vite.config.ts.timestamp-1728624798290-f3213f06e9fc.mjs:12:16)
> 2024-10-10 22:33:18     at file:///app/web/vite.config.ts.timestamp-1728624798290-f3213f06e9fc.mjs:22:24
> 2024-10-10 22:33:18     at ModuleJob.run (node:internal/modules/esm/module_job:234:25)
> 2024-10-10 22:33:18     at async ModuleLoader.import (node:internal/modules/esm/loader:473:24)
> 2024-10-10 22:33:18     at async loadConfigFromBundledFile (file:///app/web/node_modules/.pnpm/vite@5.4.3_@types+node@20.16.3_sass@1.77.8/node_modules/vite/dist/node/chunks/dep-BaOMuo4I.js:66613:15)
> 2024-10-10 22:33:18     at async loadConfigFromFile (file:///app/web/node_modules/.pnpm/vite@5.4.3_@types+node@20.16.3_sass@1.77.8/node_modules/vite/dist/node/chunks/dep-BaOMuo4I.js:66454:24)
> 2024-10-10 22:33:18     at async resolveConfig (file:///app/web/node_modules/.pnpm/vite@5.4.3_@types+node@20.16.3_sass@1.77.8/node_modules/vite/dist/node/chunks/dep-BaOMuo4I.js:66062:24)
> 2024-10-10 22:33:18     at async preview (file:///app/web/node_modules/.pnpm/vite@5.4.3_@types+node@20.16.3_sass@1.77.8/node_modules/vite/dist/node/chunks/dep-BaOMuo4I.js:65876:18) {
> 2024-10-10 22:33:18   errno: -2,
> 2024-10-10 22:33:18   code: 'ENOENT',
> 2024-10-10 22:33:18   syscall: 'open',
> 2024-10-10 22:33:18   path: '/Cargo.toml'
> 2024-10-10 22:33:18 }
> 2024-10-10 22:36:25 thread 'tokio-runtime-worker' panicked at packages/service/src/providers/igdb/provider.rs:175:38:
> 2024-10-10 22:36:25 Could not parse response: reqwest::Error { kind: Decode, source: Error("missing field `access_token`", line: 1, column: 48) }
> 2024-10-10 22:36:25 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> 2024-10-10 22:36:25 5:36:25 AM [vite] http proxy error: /retrom.MetadataService/GetIgdbSearch
> 2024-10-10 22:36:25 Error: socket hang up
> 2024-10-10 22:36:25     at Socket.socketOnEnd (node:_http_client:528:25)
> 2024-10-10 22:36:25     at Socket.emit (node:events:531:35)
> 2024-10-10 22:36:25     at endReadableNT (node:internal/streams/readable:1696:12)
> 2024-10-10 22:36:25     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
> 2024-10-10 22:37:09 Failed to read local Cargo.toml: Error: ENOENT: no such file or directory, open '/Cargo.toml'
> 2024-10-10 22:37:09     at Object.openSync (node:fs:573:18)
> 2024-10-10 22:37:09     at readFileSync (node:fs:452:35)
> 2024-10-10 22:37:09     at readLocalCargoToml (file:///app/web/vite.config.ts.timestamp-1728625029712-d3ef57059f1f6.mjs:12:16)
> 2024-10-10 22:37:09     at file:///app/web/vite.config.ts.timestamp-1728625029712-d3ef57059f1f6.mjs:22:24
> 2024-10-10 22:37:09     at ModuleJob.run (node:internal/modules/esm/module_job:234:25)
> 2024-10-10 22:37:09     at async ModuleLoader.import (node:internal/modules/esm/loader:473:24)
> 2024-10-10 22:37:09     at async loadConfigFromBundledFile (file:///app/web/node_modules/.pnpm/vite@5.4.3_@types+node@20.16.3_sass@1.77.8/node_modules/vite/dist/node/chunks/dep-BaOMuo4I.js:66613:15)
> 2024-10-10 22:37:09     at async loadConfigFromFile (file:///app/web/node_modules/.pnpm/vite@5.4.3_@types+node@20.16.3_sass@1.77.8/node_modules/vite/dist/node/chunks/dep-BaOMuo4I.js:66454:24)
> 2024-10-10 22:37:09     at async resolveConfig (file:///app/web/node_modules/.pnpm/vite@5.4.3_@types+node@20.16.3_sass@1.77.8/node_modules/vite/dist/node/chunks/dep-BaOMuo4I.js:66062:24)
> 2024-10-10 22:37:09     at async preview (file:///app/web/node_modules/.pnpm/vite@5.4.3_@types+node@20.16.3_sass@1.77.8/node_modules/vite/dist/node/chunks/dep-BaOMuo4I.js:65876:18) {
> 2024-10-10 22:37:09   errno: -2,
> 2024-10-10 22:37:09   code: 'ENOENT',
> 2024-10-10 22:37:09   syscall: 'open',
> 2024-10-10 22:37:09   path: '/Cargo.toml'
> 2024-10-10 22:37:09 }
> 2024-10-10 22:37:09 
> 2024-10-10 22:37:09 ♻️  Generating routes...
> 2024-10-10 22:37:09 ✅ Processed routes in 39ms
> 2024-10-10 22:37:09   ➜  Local:   http://localhost:3000/
> 2024-10-10 22:37:09   ➜  Network: http://172.18.0.6:3000/

Logs as soon as I try to scan library:

> 2024-10-10 22:39:13 thread 'tokio-runtime-worker' panicked at packages/service/src/providers/igdb/provider.rs:175:38:
> 2024-10-10 22:39:13 Could not parse response: reqwest::Error { kind: Decode, source: Error("missing field `access_token`", line: 1, column: 48) }
> 2024-10-10 22:39:13 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> 2024-10-10 22:39:13 5:39:13 AM [vite] http proxy error: /retrom.MetadataService/GetIgdbSearch
> 2024-10-10 22:39:13 Error: socket hang up
> 2024-10-10 22:39:13     at Socket.socketOnEnd (node:_http_client:528:25)
> 2024-10-10 22:39:13     at Socket.emit (node:events:531:35)
> 2024-10-10 22:39:13     at endReadableNT (node:internal/streams/readable:1696:12)
> 2024-10-10 22:39:13     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
> 2024-10-10 22:39:13 2024-10-11T05:39:13.750018Z  WARN update_library:update_library: retrom_service::grpc::library::update_handlers: Failed to resolve platforms: Could not read directory
> 2024-10-10 22:39:45 thread 'tokio-runtime-worker' panicked at packages/service/src/providers/igdb/provider.rs:175:38:
> 2024-10-10 22:39:45 Could not parse response: reqwest::Error { kind: Decode, source: Error("missing field `access_token`", line: 1, column: 48) }
> 2024-10-10 22:39:45 5:39:45 AM [vite] http proxy error: /retrom.MetadataService/GetIgdbSearch
> 2024-10-10 22:39:45 Error: socket hang up
> 2024-10-10 22:39:45     at Socket.socketOnEnd (node:_http_client:528:25)
> 2024-10-10 22:39:45     at Socket.emit (node:events:531:35)
> 2024-10-10 22:39:45     at endReadableNT (node:internal/streams/readable:1696:12)
> 2024-10-10 22:39:45     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

**Comment by JMBeresford** [comment] 2024-10-11 22:42
That error implies an IO error, almost always due to non-existence (e.g. the directory is not visible to the service). This leads me to believe that this is likely not a bug w/ Retrom, so I'm going to close this for now as the issues page is not for troubleshooting. I would be more than happy to help troubleshoot this in discord, however so please ping me there: https://discord.gg/tM7VgWXCdZ

In the meantime, if you could please update to Retrom 0.2.1 and examine the logs again that might help us dig deeper -- I just improved the detailing of these errors. I would also urge you to confirm that the library directory is visible to the service. I see that you verified the container can see it, but I don't see any indication of which user you used to verify this. Just to be safe, I would suggest `exec`ing into the container as the user in which retrom is running (`1505:1505` by default). Let me know in discord if you need additional assistance w/ the new logs 😄

**Closed by JMBeresford** 2024-10-11 22:42 UTC
Labels: bug
