### ISSUE TITLE
Fullscreen mode displays entries for empty libraries

### ISSUE THREAD

**Issue by Laroustine** [JMBeresford/retrom#182] opened 2024-11-17 20:42 UTC
### Describe the bug
When in fullscreen mode I cannot access the other occurrences of a console, but the games still appear in the "ALL GAMES".

### Steps To Reproduce
1. Have multiple of the same platform
2. Open Fullscreen mode

### Expected behavior
You are supossed to see as many times the platform apears in normal mode.

### Screenshots
![Fullscreen](https://cdn.discordapp.com/attachments/1307787760199008348/1307787760689479751/image.png?ex=673b93c3&is=673a4243&hm=b4025abc0ca3252b63e84cd6a285e514e1ba754aac58aca38eaf38b01fc3ff68&)
![Normal Mode](https://cdn.discordapp.com/attachments/1307787760199008348/1307787761708830840/image.png?ex=673b93c3&is=673a4243&hm=26bcc79161c3e723c5cf1220ebe9d11f2030677a1ad418aafa734a008b7ae2c6&)

### Environment (please complete the following information _where applicable_):
 - OS: Windows 10
 - Version 0.4.2

**Comment by JMBeresford** [comment] 2024-11-18 07:00
related to #169

**Comment by JMBeresford** [comment] 2024-11-18 07:01
@Laroustine For clarity, is your reason for having duplicate platform entires the same as described in the issue above? I want to make sure that I am accounting for each use case when I get to resolving these issues.

**Comment by Laroustine** [comment] 2024-11-18 13:19
Yes, some of the duplicates are because I have some multi-file games and single file games.
I also have duplicate platform due to having some games sorted on different disks.

**Comment by JMBeresford** [comment] 2024-11-19 01:54
@Laroustine I cannot reproduce this -- are you sure the duplicate entries are not in the list? It is not currently sorted, alphabetically at least, so you may need to scroll a while to find the duplicates.

The next release will have the list sorted alphabetically which should make it easier to see if they are populated or not.

**Comment by Laroustine** [comment] 2024-11-19 11:42
All my library finally appear in fullscreen mode (version 0.4.4). But empty libraries still appear in fullscreen mode.

**Comment by JMBeresford** [comment] 2024-11-19 19:17
Good to hear, I'll look into empty libraries soon

**Closed** 2024-11-22 01:28 UTC
Labels: bug
