### ISSUE TITLE
Support for Retroarch

### ISSUE THREAD

**Issue by danblu3** [JMBeresford/retrom#97] opened 2024-09-16 12:48 UTC
It seems the main desktop app has no support for Retroarch which is going to limit your audience pretty considerably. 

![image](https://github.com/user-attachments/assets/2b2c58ab-d849-46de-9e1e-20f7a932fbfd)
The above image is my attempt to configure the loading of a core, the first problem is the fact it won't accept "{file}" which means that you won't be able to launch any file with spaces in. 

Secondly, even if I trick this and make the file all one word it still does not work. Are you aware that Retroarch will not work with this system? Is there a configuration that is being missed somewhere? 

![image](https://github.com/user-attachments/assets/d204a6fd-a074-44a3-a560-7b74955db682)

**Comment by JMBeresford** [comment] 2024-09-16 20:07
Ah yes, I know why the quotes are breaking the detection of `{file}`. I'll whip up a fix for that soon. However, the quotes are unnecessary here as the client will apply quotes (and dedupe any double quotes) prior to executing the command.

Let me take some time to explore retroarch launching and see if I can see what the issue is. In the meantime, if you could download the 'debug' client from github and use that instead we could capture some logs that might make this process much smoother!

**Comment by JMBeresford** [comment] 2024-09-16 21:02
After looking, it seems like the quote handling is causing issues.

Thanks for reporting this, I'll take a further look and release a fix soon.

**Comment by JMBeresford** [comment] 2024-09-18 04:37
@danblu3 Arg parsing should be fixed in latest release `(v0.0.80)`.

I see in your screenshot that you are using a relative path for the core you want to use. That may also cause issues, as Retrom does not currently set the working directory when spawning the emulators. It may default to what you expect, it may not but I would suggest trying an absolute path if you keep getting issues.

**Comment by danblu3** [comment] 2024-09-18 12:51
Will give it a test, going to try this on my synology again as well with the suggested fixes.

**Comment by danblu3** [comment] 2024-09-18 13:37
Works beautifully, nice one. 
Good quick fix.

I have an issue with the profiles but I think that's just me wanting to be lazy.

**Comment by JMBeresford** [comment] 2024-09-18 16:51
@danblu3 Could you perhaps elaborate on the permissions issue in #95 if you feel it aligns w/ that ticket? Or open a new ticket if not?

If there truly is an issue w/ how the retrom service/web images handle permissions I would like to resolve that. If it is strictly the DB image, however, that is the official postgresql image and is not something I have control over.

Also curious to hear what you are wanting from the profiles that you are not currently able to do, but it seems like the issue at hand is resolved so I will close this.

**Closed by JMBeresford** 2024-09-18 16:51 UTC
